import type { ContentOptions } from './types'

/** Opening sentinel of the injected block in workbench HTML */
export const PATCH_BEGIN = '<!-- RTL-AGENTS-BEGIN -->'

/** Closing sentinel of the injected block in workbench HTML */
export const PATCH_END = '<!-- RTL-AGENTS-END -->'

/** CSS file name placed in the workbench directory */
export const CSS_FILENAME = 'rtl-agents.css'

/** JS file name placed in the workbench directory */
export const JS_FILENAME = 'rtl-agents.js'

/** Manifest file name placed next to the assets */
export const MANIFEST_FILENAME = 'rtl-agents.manifest.json'

/** Glyph used by both the status bar item and the injected header button */
export const TOGGLE_GLYPH = '⇄'

/** localStorage key shared by every patched document (same origin) */
export const STORAGE_KEY = 'rtl-agents-active-state'

/**
 * Chat surfaces we scope the BiDi rules to.
 * Keeping this list narrow is what stops the patch from re-aligning the editor itself.
 */
const ROOT_SELECTORS = [
  '.antigravity-agent-side-panel',
  '.rtl-agents-root',
  '.interactive-session',
  '.chat-container',
]

/**
 * Elements whose *text* should pick its own direction.
 *
 * `unicode-bidi: plaintext` makes the browser resolve direction per paragraph from
 * the first strong directional character (Unicode BiDi rules P2/P3). That is the same
 * decision the old regex made in JS, except it happens at layout time — before the
 * first paint — so streamed text never flashes LTR before flipping.
 */
const TEXT_SELECTORS = [
  'p',
  'li',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'blockquote',
  'dd',
  'dt',
  'td',
  'th',
  'figcaption',
  'summary',
  'textarea',
  '[contenteditable="true"]',
  // Antigravity renders each response paragraph as div.animate-markdown
  '.animate-markdown',
  '.whitespace-pre-wrap',
  '.markdown',
  '.markdown-body',
  '.rendered-markdown',
]

/**
 * Anything here keeps hard LTR regardless of the text it holds.
 * Listed after the BiDi rules so it wins the cascade at equal specificity.
 */
const LTR_SELECTORS = [
  'pre',
  'code',
  'kbd',
  'samp',
  '.monaco-editor',
  '.interactive-result-code-block',
  '.code-block-container',
]

function list(selectors: string[]): string {
  return selectors.join(', ')
}

/**
 * Build the RTL stylesheet. Everything is scoped behind `html.rtl-agents-on`
 * so toggling is a single class flip on the root element.
 */
export function buildCss(options: ContentOptions): string {
  const roots = list([...ROOT_SELECTORS, ...options.customSelectors])
  const text = list(TEXT_SELECTORS)
  const ltr = list(LTR_SELECTORS)

  return `/* === RTL-AGENTS-CSS-START === */
/* Generated by RTL Agents — do not edit by hand. */

/* ==========================================
   Header toggle button
   ========================================== */

#rtl-agents-toggle-btn {
  display: inline-flex !important;
  align-items: center !important;
  justify-content: center !important;
  font-size: 14px !important;
  font-weight: bold !important;
  line-height: 1 !important;
  cursor: pointer !important;
  user-select: none !important;
  text-decoration: none !important;
  transition: opacity 0.15s ease, color 0.15s ease;
}

#rtl-agents-toggle-btn:hover {
  opacity: 0.8 !important;
}

#rtl-agents-toggle-btn.rtl-agents-active {
  color: #ff9f0a !important;
}

/* ==========================================
   Per-paragraph BiDi — no JavaScript involved
   ========================================== */

html.rtl-agents-on :is(${roots}) :is(${text}) {
  unicode-bidi: plaintext !important;
  text-align: start !important;
}

/* Standalone agent window (workbench-jetski-agent.html) has no panel root:
   the whole document is the chat surface. */
html.rtl-agents-on.rtl-agents-standalone body :is(${text}) {
  unicode-bidi: plaintext !important;
  text-align: start !important;
}

/* ==========================================
   Layout safety — these never flip
   ========================================== */

html.rtl-agents-on :is(${ltr}) {
  direction: ltr !important;
  unicode-bidi: isolate !important;
  text-align: left !important;
}

/* Column order always follows source order, never the surrounding text. */
html.rtl-agents-on table {
  direction: ltr !important;
}

/* === RTL-AGENTS-CSS-END === */
`
}

/**
 * Build the injected runtime.
 *
 * Responsibilities are deliberately small: set the root class before first paint,
 * inject the header toggle button, and keep in sync with the extension host through
 * the status bar item. Text direction itself is handled entirely by CSS.
 */
export function buildJs(_options: ContentOptions): string {
  return `/* === RTL-AGENTS-JS-START === */
/* Generated by RTL Agents — do not edit by hand. */
(function () {
  'use strict';

  try {
    var DOC = document;
    var HTML = DOC.documentElement;
    var BTN_ID = 'rtl-agents-toggle-btn';
    var ON_CLASS = 'rtl-agents-on';
    var STANDALONE_CLASS = 'rtl-agents-standalone';
    var ACTIVE_CLASS = 'rtl-agents-active';
    var STORAGE_KEY = '${STORAGE_KEY}';
    var GLYPH = '\\u21C4';
    var POLL_MS = 800;
    var SELF_DESTRUCT_MS = 3000;

    /* ------------------------------------------------------------------
       Phase 0 — runs from <head>, before <body> exists.
       Setting the class here is what removes the initial LTR flash.
       ------------------------------------------------------------------ */

    var file = (location.pathname.split('/').pop() || '').toLowerCase();
    var isStandalone = file !== 'workbench.html';
    if (isStandalone) {
      HTML.classList.add(STANDALONE_CLASS);
    }

    var current = false;
    try {
      current = localStorage.getItem(STORAGE_KEY) === 'true';
    }
    catch (e) { /* storage unavailable */ }
    if (current) {
      HTML.classList.add(ON_CLASS);
    }

    /* ------------------------------------------------------------------
       State
       ------------------------------------------------------------------ */

    function syncButton() {
      var b = DOC.getElementById(BTN_ID);
      if (b) {
        b.classList.toggle(ACTIVE_CLASS, current);
        b.setAttribute('aria-pressed', current ? 'true' : 'false');
      }
    }

    function apply(on) {
      if (on === current) {
        syncButton();
        return;
      }
      current = on;
      HTML.classList.toggle(ON_CLASS, on);
      try {
        localStorage.setItem(STORAGE_KEY, on ? 'true' : 'false');
      }
      catch (e) { /* storage unavailable */ }
      syncButton();
    }

    // Keeps the main window and the standalone agent window in lockstep.
    window.addEventListener('storage', function (e) {
      if (e.key === STORAGE_KEY) {
        apply(e.newValue === 'true');
      }
    });

    /* ------------------------------------------------------------------
       Status bar bridge (main window only)

       The extension host owns the persisted state. It cannot touch this DOM and
       we cannot call into it, so the status bar item is the channel in both
       directions: we read its label, and we click it to request a toggle.
       ------------------------------------------------------------------ */

    var statusEl = null;
    var statusObserver = null;
    var sawStatus = false;
    var missingSince = 0;
    var lastStatusValue = null;

    function findStatusEl() {
      var items = DOC.querySelectorAll('.statusbar-item');
      for (var i = 0; i < items.length; i++) {
        if ((items[i].textContent || '').indexOf(GLYPH) !== -1) {
          return items[i];
        }
      }
      return null;
    }

    function readStatus(el) {
      var t = el.textContent || '';
      if (t.indexOf(GLYPH + ' RTL') !== -1) { return true; }
      if (t.indexOf(GLYPH + ' LTR') !== -1) { return false; }
      return null;
    }

    function attachStatus() {
      var el = findStatusEl();
      if (el === statusEl) { return; }

      if (statusObserver) {
        statusObserver.disconnect();
        statusObserver = null;
      }
      statusEl = el;
      if (!el) { return; }

      sawStatus = true;
      missingSince = 0;

      // Adopt the label only when it actually says something new. VS Code may
      // replace this element on re-render; re-reading an unchanged label would
      // otherwise undo a toggle we just applied locally.
      var initial = readStatus(el);
      if (initial !== null && initial !== lastStatusValue) {
        lastStatusValue = initial;
        apply(initial);
      }

      statusObserver = new MutationObserver(function () {
        var next = readStatus(el);
        if (next !== null && next !== lastStatusValue) {
          lastStatusValue = next;
          apply(next);
        }
      });
      statusObserver.observe(el, { childList: true, subtree: true, characterData: true });
    }

    /* ------------------------------------------------------------------
       Toggle button
       ------------------------------------------------------------------ */

    var ANCHORS = [
      '[data-tooltip-id="new-conversation-tooltip"]',
      '[data-tooltip-id*="new-conversation"]',
      '[data-tooltip-id*="new-chat"]',
      '[aria-label="New Conversation"]',
      '[aria-label*="New Chat"]',
      '[title*="New Conversation"]'
    ];

    function findAnchor() {
      for (var i = 0; i < ANCHORS.length; i++) {
        var el = DOC.querySelector(ANCHORS[i]);
        if (el) { return el; }
      }
      return null;
    }

    function onToggle(e) {
      if (e) {
        e.preventDefault();
        e.stopPropagation();
      }

      // Optimistic: flip immediately so the click feels instant...
      apply(!current);

      // ...then let the extension host record the authoritative state.
      var el = statusEl || findStatusEl();
      if (el) {
        var target = el.querySelector('a, .statusbar-item-label') || el;
        target.click();
      }
    }

    var hostObserver = null;

    function watchHost(host) {
      if (hostObserver) { hostObserver.disconnect(); }
      // childList on the header container only — it does not mutate while text streams.
      hostObserver = new MutationObserver(function () {
        var b = DOC.getElementById(BTN_ID);
        if (!b || !b.isConnected) { ensureButton(); }
      });
      hostObserver.observe(host, { childList: true });
    }

    function ensureButton() {
      var existing = DOC.getElementById(BTN_ID);
      if (existing && existing.isConnected) { return; }

      var anchor = findAnchor();
      if (!anchor || !anchor.parentNode) { return; }

      var btn = DOC.createElement('div');
      btn.id = BTN_ID;
      btn.setAttribute('role', 'button');
      btn.setAttribute('tabindex', '0');
      btn.setAttribute('aria-label', 'Toggle RTL / LTR');
      btn.title = 'Toggle RTL / LTR (RTL Agents)';
      btn.textContent = GLYPH;

      // Borrow the sibling's styling so the button looks native.
      var cls = typeof anchor.className === 'string' ? anchor.className : '';
      btn.className = cls.replace(/cursor-not-allowed|!?opacity-\\d+/g, '').trim();

      btn.addEventListener('click', onToggle);
      btn.addEventListener('keydown', function (e) {
        if (e.key === 'Enter' || e.key === ' ') { onToggle(e); }
      });

      anchor.parentNode.insertBefore(btn, anchor.nextSibling);
      syncButton();
      watchHost(anchor.parentNode);
    }

    /* ------------------------------------------------------------------
       Teardown

       When the extension is deactivated or uninstalled its status bar item
       disappears. That is our signal to remove the button and stand down —
       previously the button survived with nothing behind it.
       ------------------------------------------------------------------ */

    var pollTimer = null;

    function selfDestruct() {
      if (pollTimer) { clearInterval(pollTimer); pollTimer = null; }
      if (statusObserver) { statusObserver.disconnect(); statusObserver = null; }
      if (hostObserver) { hostObserver.disconnect(); hostObserver = null; }

      var b = DOC.getElementById(BTN_ID);
      if (b && b.parentNode) { b.parentNode.removeChild(b); }

      HTML.classList.remove(ON_CLASS);
      HTML.classList.remove(STANDALONE_CLASS);
      try {
        localStorage.removeItem(STORAGE_KEY);
      }
      catch (e) { /* storage unavailable */ }
    }

    function tick() {
      if (!isStandalone) {
        if (!statusEl || !statusEl.isConnected) { attachStatus(); }

        if (sawStatus && !statusEl) {
          if (!missingSince) {
            missingSince = Date.now();
          }
          else if (Date.now() - missingSince > SELF_DESTRUCT_MS) {
            selfDestruct();
            return;
          }
        }
        else {
          missingSince = 0;
        }
      }
      ensureButton();
    }

    function start() {
      tick();
      pollTimer = setInterval(tick, POLL_MS);
    }

    if (DOC.readyState === 'loading') {
      DOC.addEventListener('DOMContentLoaded', start);
    }
    else {
      start();
    }
  }
  catch (e) {
    // Never break the workbench boot sequence.
    if (typeof console !== 'undefined' && console.error) {
      console.error('[RTL Agents]', e);
    }
  }
})();
/* === RTL-AGENTS-JS-END === */
`
}

/**
 * Strip every generation of injected markup from a workbench HTML document.
 * Used both when unpatching and before re-patching, so the recovered text is
 * byte-identical to the IDE's original file.
 */
export function stripInjected(html: string): string {
  return html
    // v2 sentinel block, including the newline it introduced on both sides
    .replace(/\r?\n?[ \t]*<!-- RTL-AGENTS-BEGIN -->[\s\S]*?<!-- RTL-AGENTS-END -->[ \t]*\r?\n?/g, '')
    // v1 markup, exactly as it was written
    .replace(/\r?\n\t<!-- RTL Agents Support -->\r?\n\t<link[^>]*rtl-agents\.css[^>]*>/g, '')
    .replace(/\t<!-- RTL Agents Support -->\r?\n\t<script[^>]*rtl-agents\.js[^>]*><\/script>\r?\n/g, '')
    // defensive sweep for anything left behind
    .replace(/\r?\n?[ \t]*<!-- RTL Agents Support -->/g, '')
    .replace(/\r?\n?[ \t]*<link[^>]*rtl-agents\.css[^>]*>/g, '')
    .replace(/\r?\n?[ \t]*<script[^>]*rtl-agents\.js[^>]*><\/script>/g, '')
}

/**
 * Whether a workbench HTML document currently carries the patch.
 */
export function hasPatch(html: string): boolean {
  return html.includes(PATCH_BEGIN) || html.includes(CSS_FILENAME)
}

/**
 * Build the block injected into `<head>`.
 *
 * The script is loaded synchronously from `<head>` on purpose: it must set the
 * root class before `<body>` renders. An inline script is not an option — the
 * workbench CSP allows `script-src 'self'` but not `'unsafe-inline'`.
 */
export function buildInjection(relativeCssPath: string, relativeJsPath: string): string {
  return `\n\t${PATCH_BEGIN}\n`
    + `\t<link rel="stylesheet" href="${relativeCssPath}">\n`
    + `\t<script src="${relativeJsPath}"></script>\n`
    + `\t${PATCH_END}\n`
}
